name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1" # optional: defaults to us-east-1
          SOURCE_DIR: "dist" # optional: defaults to entire repository


      # - name: Deploy to S3
      #   uses: jakejarvis/s3-sync-action@v0.6.0
      #   with:
      #     aws-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: 'ap-south-1'  # Replace with your desired region
      #     source-dir: 'dist'
      #     dest-dir: 'react-aws-demo-s3'  # Replace with your S3 bucket path
